[package]
name = "fft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.15.0"
plotters = "^0.3.1"
rand = "0.8.0"
wav = "1.0.0"
ndarray = "0.15.4"
